FlaskApp/Website/views.py
from flask import Blueprint, render_template, request, flash, jsonify, redirect, url_for
from flask_login import login_required, current_user
from .models import Contact
from .webforms import SearchForm
from . import db
import json

# define a blueprint for flask application
views = Blueprint("views", __name__)


@views.route("/", methods=["GET", "POST"])
@login_required
def contactlist():
    """
    renders an html template for the contact list page. if post is received, adds new contact to database.
    
    Returns:
        -  html code of contact list page.
    """
    form = SearchForm()
    if request.method == "POST":
        first_name = request.form.get("first_name")
        last_name = request.form.get("last_name")
        number = request.form.get("number")
        photo = request.form.get("photo")
        if len(first_name) < 2:
            flash("First name must contain at least 2 characters.", category="error")
        if len(last_name) < 2:
            flash("First name must contain at least 2 characters.", category="error")
        else:
            new_contact = Contact(
                first_name=first_name,
                last_name=last_name,
                number=number,
                user_id=current_user.id,
                photo=photo,
            )
            db.session.add(new_contact)
            db.session.commit()
            flash("Contact Added", category="success")

    return render_template("contactlist.html", user=current_user, form=form)


@views.route("/delete-contact", methods=["POST"])
def delete_contact():
    """
    deletes a contact from the database.
    
    Returns:
        - dict: empty JSON response.
    """
    contact = json.loads(request.data)
    contactId = contact["contactId"]
    contact = Contact.query.get(contactId)
    if contact:
        if contact.user_id == current_user.id:
            db.session.delete(contact)
            db.session.commit()

    return jsonify({})


@views.route("/update/<int:id>", methods=["GET", "POST"])
def update(id):
    """
    updates an already existing contact in the database.
    
    Args:
        - id (int): id of contact that is to be updated.
        
    Returns:
        - redirect: redirects to contact page.
        - str: error message if a an error occurs while updating.
    """
    form = SearchForm()
    contact = Contact.query.get(id)
    if request.method == "POST":
        contact.first_name = request.form.get("first_name")
        contact.last_name = request.form.get("last_name")
        contact.number = request.form.get("number")
        contact.photo = request.form.get("photo")
        print("First Name:", contact.first_name)
        print("Last Name:", contact.last_name)
        try:
            db.session.commit()
            return redirect("/")
        except:
            return "There was a problem updating"
    else:
        return render_template("update.html", contact=contact, user=current_user, form = form)



#search function
@views.route('/search', methods = ["POST"])
def search():
    """
    searches for contacts in database.
    
    Returns:
        - html template for search results page.
    """
    form = SearchForm()
    contacts = Contact.query
    if form.validate():
        searched = form.searched.data 
        contacts = contacts.filter(Contact.first_name.like('%' + searched + '%'))
        contacts = contacts.order_by(Contact.first_name).all()
        return render_template("search.html", form = form, searched = searched, contacts = contacts)
    
@views.context_processor
def inject_user():
    """
    injects the current for jinja templates.
    
    Returns:
        - dict: contains current user.
    """
    return dict(user=current_user)

FlaskApp/Website/templates/base.html
<!DOCTYPE html>

<html>

    <head>
        <meta charset="utf-8" />
        <meta name ="viewport" content ="width=device-width, initial-scale=1" />
        <link rel="stylesheet" href="../static/css/style.css">
        <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
      integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh"
      crossorigin="anonymous"
        />
        <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
      crossorigin="anonymous"
        /> 
    <title>{% block title %}BODY{% endblock %}</title>
    </head>

    

    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
          <img class="d-inline-block aling-top" src="https://cdn-icons-png.flaticon.com/512/5439/5439135.png" width="30" height="30">
          <span class="navbar-brand mb-0 h1">Phonebook</span>
            <button class="navbar-toggler" 
                    type="button" 
                    data-toggle="collapse" 
                    data-target="#navbar">
                <span class ="navbar-toggler-icon"></span>
            </button>
        
            <div class="collapse navbar-collapse">
                <div class="navbar-nav">
                    {% if user.is_authenticated %}
                    <a class="nav-item nav-link" id="home" href="/">Contacts</a>
                    <a class="nav-item nav-link" id="logout" href="/logout">Logout</a>
                    <form method="POST" action="{{ url_for('views.search') }}" class="d-flex">
                      {{ form.hidden_tag() }}
                      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searched">
                      <button class="btn btn-outline-secondary" type="submit">Search</button>
                  </form>
                    {% else %}
                    <a class="nav-item nav-link" id="login" href="/login">Login</a>
                    <a class="nav-item nav-link" id="signUp" href="/signup">Sign Up</a>

                    {% endif %}
                    
                </div>               
            </div>
        </nav>

        {% with messages = get_flashed_messages(with_categories=true) %}
        {% if messages %}
          {% for category, message in messages %}
          {% if category == 'error' %}
          <div class="alert alert-danger alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% else %}
          <div class="alert alert-success alter-dismissable fade show" role="alert">
            {{ message }}
            <button type="button" class="close" data-dismiss="alert">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          {% endif %}
          {% endfor %}
        {% endif %}
        {% endwith %}

        <div class ="container">
            {% block content %}
            {% endblock %}

        </div>

        <script
        src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"
      ></script>
      <script
        src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"
      ></script>
      
    <script type="text/javascript"
      src="{{ url_for('static', filename='index.js') }}">
    </script>

    </body>


</html>

FlaskApp/Website/templates/contactlist.html
{%extends "base.html" %}{% block title %}Contacts{% endblock %}{% block content %}
<!-- <h1 align = "center">Contacts</h1>
<ul class = "list-group list-group-flush" id="contacts">
    {% for contact in user.contacts %}
    <li class = "list-group-item">{{ contact.first_name }}
    <li class = "list-group-item">{{ contact.last_name }}</li>
    <li class = "list-group-item">{{ contact.number }}</li>
    <br\>
    {% endfor %}
</ul> -->
<br/>
<h4 align="center">Contacts</h4>
<div class="container">
  <div class="row">
    {% for contact in user.contacts|sort(attribute='first_name') %}
    <div class="col-md-4">
      <div class="card">
        <div class="card-body">
          <img class="img-thumbnail" src="{{contact.photo}}" />
          <h5 class="card-title">{{ contact.first_name }} {{ contact.last_name }}</h5>
          <p class="card-text">Number: {{ contact.number }}</p>
          <button type = "button" class="close" onClick ="deleteContact({{ contact.id }})">
            <span aria-hidden="true">&times;</span>
          </button>
          <a href="/update/{{contact.id}}" class="btn btn-outline-secondary btn-sm">Update</a>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>


<br/>
<div class="container"  style="margin: 20px; padding: 20px;">
  <div class="row justify-content-center">
    <div class="col-md-6">
  <h4 class="text-center mb-4">Create New Contact</h4>
  <form method="POST" class="my-div rounded p-4">
    <div class="form-group">
      <label for="first_name">First Name</label>
      <input type="text" class="form-control" id="first_name" name="first_name">
    </div>
    <div class="form-group">
      <label for="last_name">Last Name</label>
      <input type="text" class="form-control" id="last_name" name="last_name">
    </div>
    <div class="form-group">
      <label for="number">Number</label>
      <input type="text" class="form-control" id="number" name="number">
    </div>
    <div class="form-group">
      <label for="photo">Add Link to Photo for Contact</label>
      <input type="text" class="form-control" id="photo" name="photo">
    </div>
    <div class="text-center">
      <button type="submit" class="btn btn-primary">Create Contact</button>
    </div>
  </form>
</div>

{% endblock %}

FlaskApp/Website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
  %}
  <div class="container">
    <div class="container">
      <div class="row justify-content-center">
        <div class="col-md-6">
          <div class="my-div rounded-lg" style="margin: 20px; padding: 20px;">
            <form method="POST">
              <h3 style="text-align: center;">Login</h3>
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-12">
                    <label for="email">Email Address:</label>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <input
                      type="email"
                      class="form-control"
                      id="email"
                      name="email"
                    />
                  </div>
                </div>
              </div>
              <div class="form-group">
                <div class="row">
                  <div class="col-sm-12">
                    <label for="password">Password:</label>
                  </div>
                </div>
                <div class="row">
                  <div class="col-sm-12">
                    <input
                      type="password"
                      class="form-control"
                      id="password"
                      name="password"
                    />
                  </div>
                </div>
              </div>
              <button type="submit" class="btn btn-primary">Login</button>
            </form>
          </div>
        </div>
      </div>
    </div>
    
  {% endblock %}

FlaskApp/Website/templates/search.html
{% extends "base.html" %} 

{% block content%}

    <br/>
    <h2>You searched for...</h2>
    <p>{{ searched }}</p>
    <br/>

    {% for contact in contacts %}
        <div class ="contact">
            <p>First Name: {{ contact.first_name}}</p>
            <p>Last Name: {{ contact.last_name}}</p>
            <p>Number: {{ contact.number }}</p>
        </div>
        

    {% endfor %}

{% endblock %} 

FlaskApp/Website/templates/signUp.html
{% extends "base.html" %} {% block title %}Sign Up{% endblock %} {% block
  content %}
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-md-6">
        <div class="my-div rounded-lg" style="margin: 20px; padding: 20px;">
          <form method="POST">
            <h3 style="text-align: center;">Sign Up</h3>
            <div class="form-group">
              <label for="email">Email Address:</label>
              <input
                type="email"
                class="form-control"
                id="email"
                name="email"
              />
            </div>
            <div class="form-group">
              <label for="firstName">First Name:</label>
              <input
                type="text"
                class="form-control"
                id="firstName"
                name="firstName"
              />
            </div>
            <div class="form-group">
              <label for="password1">Password:</label>
              <input
                type="password"
                class="form-control"
                id="password1"
                name="password1"
              />
            </div>
            <div class="form-group">
              <label for="password2">Confirm Password:</label>
              <input
                type="password"
                class="form-control"
                id="password2"
                name="password2"
              />
            </div>
            <br />
            <button type="submit" class="btn btn-primary">Create Account</button>
          </form>
        </div>
      </div>
    </div>
  </div>
  
  {% endblock %}

FlaskApp/Website/templates/update.html
{% extends "base.html" %}
{% block title %}Update Contact{% endblock %}
{% block content %}
<div class="container" style="margin: 20px; padding: 20px;">
  <div class="row justify-content-center">
   <div class="col-md-6">
    <h4 align="center">Update Contact</h4>
    <ul class="list-group list-group-flush" id="contacts"></ul>
    <form action="/update/{{ contact.id }}" method="POST">
        <p>First Name</p>
        <input name="first_name" id="first_name" class="form-control" value="{{ contact.first_name }}">
        <p>Last Name</p>
        <input name="last_name" id="last_name" class="form-control" value="{{ contact.last_name }}">
        <p>Number</p>
        <input name="number" id="number" class="form-control" value="{{ contact.number }}">
        <br>
        <p>Add Link to Photo for Contact</p>
        <input type="text" class="form-control" id="photo" name="photo">
        <br/>
        <div align="center">
            <button type="submit" class="btn btn-primary">Update Contact</button>
        </div>
        <br>
    </form>
    </div>
  </div>
</div>
{% endblock %}